version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
      - postgres
    networks:
      - laravel

  postgres:
    env_file: .env
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres_example}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "5434:5434"
    networks:
      - laravel
    restart: unless-stopped

  pgadmin:
    depends_on:
      - postgres
    env_file: .env
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - laravel
    restart: unless-stopped

  mysql:
    image: mysql:8.0.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3406:3306"
    environment:
      TZ: 'Asia/Tashkent'
      MYSQL_DATABASE: humdon
      MYSQL_USER: humdon
      MYSQL_PASSWORD: 8KBVRQbfM5qiZNBz
      MYSQL_ROOT_PASSWORD: 8KBVRQbfM5qiZNBz
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  #  postgres:
  #    image: postgres:14-alpine
  #    container_name: postgres
  #    restart: unless-stopped
  #    tty: true
  #    environment:
  #      TZ: 'Asia/Tashkent'
  #      POSTGRES_USER: 'postgres'
  #      POSTGRES_PASSWORD: '8KBVRQbfM5qiZNBz'
  #      POSTGRES_DB: 'humdon'
  #    ports:
  #      - "5432:5432"
  #    networks:
  #      - laravel
  #
  #  pgadmin:
  #    image: dpage/pgadmin4
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: humdon@gmail.com
  #      PGADMIN_DEFAULT_PASSWORD: 8KBVRQbfM5qiZNBz
  #    ports:
  #      - "8081:80"
  #    links:
  #      - postgres
  #    depends_on:
  #      - postgres

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: 8KBVRQbfM5qiZNBz
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - "8081:80"
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel
